### ISSUE TITLE
Change to dpi?

### ISSUE THREAD

**Issue by melriksdesign** [antipalindrome/Photoshop-Export-Layers-to-Files-Fast#177]
Wonderful script.  I see controls for Scale (width and height) and Quality (compression).  Is there a way to change the dpi before saving?

We double purpose the psd files so the original psd is set to 160 dpi. I'd like to safe-to-file at 72 dpi.

**Comment by melriksdesign** [comment]
I found a hacky way to adjust it.  Line 742.
The second null needs to be changed from 'null' to '72'.
app.activeDocument.resizeImage(UnitValue(width, "px"), null, 72, ResampleMethod.BICUBICSHARPER);

**Comment by hsw107** [comment]
Thanks for this, maybe we can add an option in the future to customize this through the dialog. Glad you found a workaround.

**Comment by Stellablue15** [comment]
Hello! I'm wondering if there's a way to save out pngs with the native resolution of the source file. My source file is 300ppi and similar to the above I'd like the resulting output to have the same (300ppi) resolution. I tried the above tweak editing the code to '300' instead of '72' but it's still resulting in a 72ppi export. 
thank you

**Comment by antipalindrome** [comment]
Unfortunately we cannot save PNGs at any other ppi. This is a photoshop limitation if I recall correctly.

**Comment by Stellablue15** [comment]
Bummer! Thanks so much for following up with me.-joeSent from my iPhoneOn Sep 24, 2022, at 9:46 PM, Hanna ***@***.***> wrote:﻿
Closed #177 as completed.
